version: '3'
services:
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod
    api:
        build: ./api
        expose: 
            - 4000
        ports:
            - "4000:4000"
        volumes:
            - ./api:/api
            - /api/node_modules
        command: nodemon server
    client:
        build: ./client
        expose: 
            - 3000
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - mongodb
        depends_on:
            - mongodb
        command: npm start
    